### PR TITLE
Add events

### PR DESCRIPTION
**Pull request by Mulugruntz**
This adds a new directory: `dvalin-tools`, where we can put our different tools. I used Python, as it's my domain of expertise.
Future PRs can improve the CLI to have them all with a single end-point. Also, reusable, automated, etc...

I'll create new (smaller PRs for follow-ups).

This PR adds the tools for `Events` retrieval.

### CODE REVIEW

**Comment by Mulugruntz** [comment]
As mentioned in https://discord.com/channels/1187462848075550720/1188216994059796490/1203337695082975232 I'm out of space to download the images.

Technically, we could also have this in a different PR. That would make sense.

**Comment by Mulugruntz** [comment]
@LudovicMalot I'll need a review on this one. You can also read the chat to have more context.

**Comment by LudovicMalot** [comment]
Parsing is good. The folder structure is good too.
- We used `pascalCase` for fields and `CamelCase` for id as we followed the GOOD format. It's not mandatory for raw data but would be preferable just for consistency. If it's too much work then leave it like that. 
- We use typescript type and then generate a schema with the npm script. It's easier for devs (and us) to modify and read those. If you could do that, that would be great, especially since an old `Events.ts` is still present and will override your change.

**Comment by Mulugruntz** [comment]
Thanks @LudovicMalot 
I'm trying to understand this typescript syntax. There's no enum so far? Is that just not possible?
I see this: https://github.com/dval-in/dvalin-data/blob/main/types/globals.d.ts
But it seems unused?

**Comment by LudovicMalot** [comment]
> Thanks @LudovicMalot I'm trying to understand this typescript syntax. There's no enum so far? Is that just not possible? I see this: https://github.com/dval-in/dvalin-data/blob/main/types/globals.d.ts But it seems unused.

It's completely possible. Yes the `global.d.ts` is unused but this file will be changed in the future. The converter supports those : 
- interface and class
- enum
- union, tuple, type[]
- Date, RegExp, URL
- string, boolean, number
- "value", 123, true, false, null, undefined literals
- type aliases
- generics
- typeof
- keyof
- conditional types

The only specificity is that we have to add the 
```
/**
* @TJS-required
*/
``` 
at the beginning of a class or interface. This indicates that all non-optional fields are required. I haven't found a more convenient way to set this up for now.

**Comment by Mulugruntz** [comment]
> * We used `pascalCase` for fields and `CamelCase` for id as we followed the GOOD format. It's not mandatory for raw data but would be preferable just for consistency. If it's too much work then leave it like that.

@LudovicMalot 

Hmm, you mean `PascalCase` and `camelCase`, right?

And for `id`, you mean the identifier of the item/character/etc?
So, instead of:
```json
  {
    "post_id": "635063",
    "game_id": "GENSHIN_IMPACT",
    "message_type": "INFO",
    "created_at": "2021-08-04T06:01:01",
    "tags": [
      "CHARACTER_TEASER"
    ],
    ...
    "article_url": "https://www.hoyolab.com/article/635063"
  }
```

it would become:

```json
  {
    "postId": "635063",
    "gameId": "GenshinImpact",
    "messageType": "Info",
    "createdAt": "2021-08-04T06:01:01",
    "tags": [
      "CharacterTeaser"
    ],
    ...
    "articleUrl": "https://www.hoyolab.com/article/635063"
  }
```

Basically, keys are `camelCase` and values are `PascalCase` when they're identifers, is that correct?

**Comment by LudovicMalot** [comment]
Yes sorry for the confusion 😅. That's exactly what I meant

**Comment by Mulugruntz** [comment]
@LudovicMalot Okay, I created a converted to generate the `types/Events.ts` file.
Not sure then how to generate the schema from this one.

**Comment by LudovicMalot** [comment]
> @LudovicMalot Okay, I created a converted to generate the `types/Events.ts` file. Not sure then how to generate the schema from this one.

@Mulugruntz simply run the `npm run schemas` scripts. It will auto-generate Schema based on the type defined in the tye folder

**Comment by Mulugruntz** [comment]
@LudovicMalot 
You can re-review.

The generated Python -> TS -> json schema works. It manages to validate the data.
Source: https://www.jsonschemavalidator.net/s/NOL5aIqf

**Review by LudovicMalot — APPROVED** [review]
all good - if it's good for you I will merge it

**Pull request merged**
